### ISSUE TITLE
Causality fix

### ISSUE THREAD

**Issue by Conaclos** [coast-team/mute-core#4]
Severity: high
Kind: divergence

# Problem

Let three participants Alice, Bob, and Carol.
1. Alice adds a block of text B1
2. Bob receives the block and removes it
3. Carol receives the removal before the addition

Alice and Bob have an empty document, while Carol has a document which includes B1. This leads to a divergence.

# Background

MUTE ensures a FIFO delivery.

# Possible fix

Upon the reception of an operation, a version vector (state vector) `context` is updated. FIFO delivery ensures that each clock monotonically increases.

Upon the generation of a removal, we add the last operation of the author of the removed block as a dependency. Upon the delivery of a removal, the application of the removal is delayed until its dependency was applied.

```ts
type ReplicaId = number
type Clock = number
type Block = {author: ReplicaId}
type Addition = {clock: Clock, block: Block}
type Removal = {clock: Clock, block: Block, dep: Clock}
type VersionVector = Map<ReplicaId, Clock>

declare const context: VersionVector

upon delivery (op: Removal) {
  wait op.dep <= context.get(op.block.author)
}

upon sending (op: Removal) {
  op.dep = context.get(op.block.author)
}
```

**Comment by kalitine** [comment]
Fix in v1.0.0.
